import { Project } from '@/types/project';
import { StudentProfile } from '@/types/user';

export const CURRENT_USER: StudentProfile = {
  id: 'usr_curr_01',
  email: 'alex.chen@stanford.edu',
  fullName: 'Alex Chen',
  headline: 'Full-Stack Developer & Product Builder',
  college: 'Stanford University',
  major: 'Computer Science',
  gradYear: 2026,
  experienceLevel: 'junior',
  workingStyle: 'collaborative',
  bio: 'CS junior focused on distributed frontend systems, reactive UI architectures, and human-computer interfaces.',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  githubUrl: 'https://github.com/alexchen',
  portfolioUrl: 'https://alexchen.dev',
  linkedinUrl: 'https://linkedin.com/in/alexchen',
  skills: [
    { id: 'sk_ts', name: 'TypeScript', category: 'frontend', proficiency: 4, yearsExperience: 2.5, verified: true },
    { id: 'sk_next', name: 'Next.js', category: 'frontend', proficiency: 4, yearsExperience: 2.0, verified: true },
    { id: 'sk_react', name: 'React', category: 'frontend', proficiency: 5, yearsExperience: 3.0, verified: true },
    { id: 'sk_tailwind', name: 'Tailwind CSS', category: 'frontend', proficiency: 5, yearsExperience: 2.0, verified: true },
    { id: 'sk_postgres', name: 'PostgreSQL', category: 'backend', proficiency: 3, yearsExperience: 1.5, verified: false },
    { id: 'sk_figma', name: 'UI/UX Design', category: 'design', proficiency: 3, yearsExperience: 1.0, verified: true },
    { id: 'sk_python', name: 'Python', category: 'backend', proficiency: 3, yearsExperience: 2.0, verified: false },
  ],
  interests: [
    { id: 'int_ai', name: 'AI & Human Interaction', category: 'ai' },
    { id: 'int_sys', name: 'Distributed Systems', category: 'systems' },
    { id: 'int_fintech', name: 'Fintech & Tooling', category: 'tools' },
  ],
  availability: {
    hoursPerWeek: 15,
    timezone: 'PST (UTC-8)',
    prefersRemote: true,
    weekendAvailability: true,
    weekdayEvenings: true,
    scheduleWindows: [
      { day: 'monday', startTime: '18:00', endTime: '22:00' },
      { day: 'wednesday', startTime: '18:00', endTime: '22:00' },
      { day: 'saturday', startTime: '10:00', endTime: '17:00' },
    ],
  },
};

export const MOCK_STUDENTS: StudentProfile[] = [
  CURRENT_USER,
  {
    id: 'usr_02',
    email: 'maya.patel@mit.edu',
    fullName: 'Maya Patel',
    headline: 'ML Researcher & PyTorch Specialist',
    college: 'MIT',
    major: 'EECS & AI',
    gradYear: 2025,
    experienceLevel: 'senior',
    workingStyle: 'structured',
    bio: 'Senior doing research in multi-modal vision-language models and edge inference optimization.',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    githubUrl: 'https://github.com/mayapatel',
    skills: [
      { id: 'sk_pytorch', name: 'PyTorch', category: 'ml_ai', proficiency: 5, yearsExperience: 3.5, verified: true },
      { id: 'sk_python', name: 'Python', category: 'backend', proficiency: 5, yearsExperience: 4.0, verified: true },
      { id: 'sk_cuda', name: 'CUDA', category: 'ml_ai', proficiency: 3, yearsExperience: 1.5, verified: true },
      { id: 'sk_transformers', name: 'Hugging Face', category: 'ml_ai', proficiency: 4, yearsExperience: 2.0, verified: true },
    ],
    interests: [
      { id: 'int_vision', name: 'Computer Vision', category: 'ai' },
      { id: 'int_robotics', name: 'Autonomous Robotics', category: 'hardware' },
    ],
    availability: {
      hoursPerWeek: 12,
      timezone: 'EST (UTC-5)',
      prefersRemote: true,
      weekendAvailability: true,
      weekdayEvenings: false,
      scheduleWindows: [
        { day: 'tuesday', startTime: '16:00', endTime: '20:00' },
        { day: 'thursday', startTime: '16:00', endTime: '20:00' },
        { day: 'sunday', startTime: '12:00', endTime: '16:00' },
      ],
    },
  },
  {
    id: 'usr_03',
    email: 'marcus.vance@berkeley.edu',
    fullName: 'Marcus Vance',
    headline: 'Systems & Embedded Rust Engineer',
    college: 'UC Berkeley',
    major: 'Computer Science',
    gradYear: 2026,
    experienceLevel: 'junior',
    workingStyle: 'fast-paced',
    bio: 'Low-level systems hacker. Building real-time micro-kernels and high-throughput protocol bridges in Rust.',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    githubUrl: 'https://github.com/marcusv',
    skills: [
      { id: 'sk_rust', name: 'Rust', category: 'backend', proficiency: 5, yearsExperience: 3.0, verified: true },
      { id: 'sk_cpp', name: 'C/C++', category: 'hardware', proficiency: 4, yearsExperience: 2.5, verified: true },
      { id: 'sk_grpc', name: 'gRPC & WebSockets', category: 'backend', proficiency: 4, yearsExperience: 2.0, verified: true },
      { id: 'sk_docker', name: 'Docker & Linux', category: 'systems', proficiency: 4, yearsExperience: 2.5, verified: true },
    ],
    interests: [
      { id: 'int_sys', name: 'Distributed Systems', category: 'systems' },
      { id: 'int_iot', name: 'Hardware & IoT', category: 'hardware' },
    ],
    availability: {
      hoursPerWeek: 18,
      timezone: 'PST (UTC-8)',
      prefersRemote: false,
      weekendAvailability: true,
      weekdayEvenings: true,
      scheduleWindows: [
        { day: 'monday', startTime: '19:00', endTime: '23:00' },
        { day: 'wednesday', startTime: '19:00', endTime: '23:00' },
        { day: 'friday', startTime: '19:00', endTime: '23:00' },
        { day: 'saturday', startTime: '13:00', endTime: '19:00' },
      ],
    },
  },
  {
    id: 'usr_04',
    email: 'elena.rostova@cmu.edu',
    fullName: 'Elena Rostova',
    headline: 'Interaction Designer & Design Systems Lead',
    college: 'Carnegie Mellon University',
    major: 'Human-Computer Interaction',
    gradYear: 2025,
    experienceLevel: 'senior',
    workingStyle: 'mentor-oriented',
    bio: 'Designing interfaces that feel tactile, responsive, and humane. Passionate about typography and design systems.',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    portfolioUrl: 'https://elenadesign.space',
    skills: [
      { id: 'sk_figma', name: 'UI/UX Design', category: 'design', proficiency: 5, yearsExperience: 4.0, verified: true },
      { id: 'sk_design_sys', name: 'Design Systems', category: 'design', proficiency: 5, yearsExperience: 3.0, verified: true },
      { id: 'sk_tailwind', name: 'Tailwind CSS', category: 'frontend', proficiency: 4, yearsExperience: 2.0, verified: true },
      { id: 'sk_threejs', name: 'Three.js / 3D', category: 'design', proficiency: 3, yearsExperience: 1.5, verified: false },
    ],
    interests: [
      { id: 'int_hci', name: 'HCI & Spatial Design', category: 'design' },
      { id: 'int_edtech', name: 'Accessible EdTech', category: 'social' },
    ],
    availability: {
      hoursPerWeek: 10,
      timezone: 'EST (UTC-5)',
      prefersRemote: true,
      weekendAvailability: false,
      weekdayEvenings: true,
      scheduleWindows: [
        { day: 'tuesday', startTime: '18:00', endTime: '22:00' },
        { day: 'thursday', startTime: '18:00', endTime: '22:00' },
      ],
    },
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj_01',
    ownerId: 'usr_02',
    owner: MOCK_STUDENTS[1],
    title: 'EchoSpatial: Spatial Audio for Visual Impairment',
    tagline: 'Real-time LiDAR depth mapping converted into directional 3D audio cues.',
    description: 'We are engineering an iOS and wearable spatial audio beacon system that translates LiDAR point clouds into synthesized binaural soundscapes. It enables visually impaired students to navigate indoor university buildings autonomously with sub-meter acoustic precision.',
    category: 'Assistive Tech & Vision',
    status: 'recruiting',
    maxTeamSize: 4,
    durationWeeks: 8,
    hoursPerWeek: 12,
    bannerUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    githubRepo: 'https://github.com/echospatial/core',
    demoUrl: 'https://echospatial.internal.io',
    requiredSkills: [
      { skill: { id: 'sk_ts', name: 'TypeScript', category: 'frontend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_react', name: 'React', category: 'frontend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_pytorch', name: 'PyTorch', category: 'ml_ai' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_figma', name: 'UI/UX Design', category: 'design' }, requiredProficiency: 3, importance: 'preferred' },
    ],
    slots: [
      { id: 'slot_1', roleTitle: 'Spatial ML Lead', assignedMember: MOCK_STUDENTS[1], requiredSkills: ['PyTorch', 'Python'], isFilled: true },
      { id: 'slot_2', roleTitle: 'Lead Web/App Architect', requiredSkills: ['TypeScript', 'React', 'Next.js'], isFilled: false },
      { id: 'slot_3', roleTitle: 'HCI & Accessibility Designer', requiredSkills: ['UI/UX Design', 'Figma'], isFilled: false },
      { id: 'slot_4', roleTitle: 'Acoustics & DSP Engineer', requiredSkills: ['C/C++', 'DSP'], isFilled: false },
    ],
    missingRoles: ['Lead Web/App Architect', 'HCI & Accessibility Designer'],
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-08-24T14:30:00Z',
    matchScore: 94,
    matchHighlights: [
      'Top skill match: TypeScript (Level 4) & React (Level 5)',
      '15h/wk exceeds 12h/wk requirement',
      'High assistive tech interest alignment',
    ],
    matchBreakdown: {
      skillMatch: 95,
      experienceMatch: 90,
      availabilityMatch: 100,
      interestMatch: 95,
      roleMatch: 90,
    },
  },
  {
    id: 'proj_02',
    ownerId: 'usr_03',
    owner: MOCK_STUDENTS[2],
    title: 'KubePulse: Zero-Overhead Distributed Cluster Mesh',
    tagline: 'Lightweight, single-binary container orchestration engine for student labs.',
    description: 'Existing cluster engines consume 2GB+ per node just for control planes. KubePulse is built ground-up in Rust with eBPF telemetry to run resilient distributed workloads on recycled campus hardware under 30MB baseline RAM.',
    category: 'Systems & Infrastructure',
    status: 'recruiting',
    maxTeamSize: 3,
    durationWeeks: 10,
    hoursPerWeek: 15,
    bannerUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    githubRepo: 'https://github.com/kubepulse/core',
    requiredSkills: [
      { skill: { id: 'sk_rust', name: 'Rust', category: 'backend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_ts', name: 'TypeScript', category: 'frontend' }, requiredProficiency: 3, importance: 'preferred' },
      { skill: { id: 'sk_tailwind', name: 'Tailwind CSS', category: 'frontend' }, requiredProficiency: 3, importance: 'nice_to_have' },
    ],
    slots: [
      { id: 'slot_2_1', roleTitle: 'Core Systems & eBPF Lead', assignedMember: MOCK_STUDENTS[2], requiredSkills: ['Rust', 'C/C++'], isFilled: true },
      { id: 'slot_2_2', roleTitle: 'Dashboard & Visualizer Engineer', requiredSkills: ['TypeScript', 'Next.js', 'Tailwind CSS'], isFilled: false },
      { id: 'slot_2_3', roleTitle: 'Distributed Testing Engineer', requiredSkills: ['Docker', 'Linux', 'Rust'], isFilled: false },
    ],
    missingRoles: ['Dashboard & Visualizer Engineer'],
    createdAt: '2026-08-18T16:00:00Z',
    updatedAt: '2026-08-23T11:20:00Z',
    matchScore: 86,
    matchHighlights: [
      'Frontend & Dashboard builder needed',
      'Perfect schedule fit (15h/wk)',
      'Direct match for TypeScript + Tailwind',
    ],
    matchBreakdown: {
      skillMatch: 82,
      experienceMatch: 88,
      availabilityMatch: 100,
      interestMatch: 85,
      roleMatch: 85,
    },
  },
  {
    id: 'proj_03',
    ownerId: 'usr_04',
    owner: MOCK_STUDENTS[3],
    title: 'OmniCampus: Decentralized University Course Graph',
    tagline: 'Interactive 3D graph connecting prerequisite pathways and research labs.',
    description: 'Course catalogs are static PDFs. OmniCampus parses thousands of syllabus documents across 12 universities into a semantic prerequisite graph with interactive WebGL visualization, community course reviews, and workload balancing.',
    category: 'EdTech & Knowledge Graphs',
    status: 'recruiting',
    maxTeamSize: 4,
    durationWeeks: 6,
    hoursPerWeek: 10,
    bannerUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    githubRepo: 'https://github.com/omnicampus/graph',
    requiredSkills: [
      { skill: { id: 'sk_next', name: 'Next.js', category: 'frontend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_postgres', name: 'PostgreSQL', category: 'backend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_ts', name: 'TypeScript', category: 'frontend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_figma', name: 'UI/UX Design', category: 'design' }, requiredProficiency: 4, importance: 'preferred' },
    ],
    slots: [
      { id: 'slot_3_1', roleTitle: 'Design & Interaction Lead', assignedMember: MOCK_STUDENTS[3], requiredSkills: ['UI/UX Design', 'Figma'], isFilled: true },
      { id: 'slot_3_2', roleTitle: 'Full-Stack Next.js Architect', requiredSkills: ['Next.js', 'TypeScript', 'PostgreSQL'], isFilled: false },
      { id: 'slot_3_3', roleTitle: 'Graph Algorithm & Data Pipeline', requiredSkills: ['Python', 'PostgreSQL'], isFilled: false },
    ],
    missingRoles: ['Full-Stack Next.js Architect'],
    createdAt: '2026-08-22T08:00:00Z',
    updatedAt: '2026-08-25T02:15:00Z',
    matchScore: 97,
    matchHighlights: [
      'Exact tech stack alignment: Next.js + TypeScript + PostgreSQL',
      'High demand for full-stack role',
      'Active Stanford/CMU cross-campus collaboration',
    ],
    matchBreakdown: {
      skillMatch: 98,
      experienceMatch: 95,
      availabilityMatch: 100,
      interestMatch: 96,
      roleMatch: 98,
    },
  },
  {
    id: 'proj_04',
    ownerId: 'usr_02',
    owner: MOCK_STUDENTS[1],
    title: 'BioFlow: Microfluidics Simulation Playground',
    tagline: 'GPU-accelerated droplet physics engine running directly in browser WebGPU.',
    description: 'Democratizing lab-on-a-chip prototyping. Instead of weeks of physical cleanroom trial-and-error, BioFlow allows bioengineering students to simulate microfluidic laminar flow, droplet merging, and cell sorting in sub-millisecond frames.',
    category: 'Biotech & Scientific Computing',
    status: 'recruiting',
    maxTeamSize: 4,
    durationWeeks: 12,
    hoursPerWeek: 16,
    bannerUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop&q=80',
    requiredSkills: [
      { skill: { id: 'sk_webgpu', name: 'WebGPU / WGSL', category: 'frontend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_ts', name: 'TypeScript', category: 'frontend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_python', name: 'Python', category: 'backend' }, requiredProficiency: 3, importance: 'preferred' },
    ],
    slots: [
      { id: 'slot_4_1', roleTitle: 'Physics & Simulation Lead', requiredSkills: ['WebGPU', 'C++'], isFilled: false },
      { id: 'slot_4_2', roleTitle: 'Web Frontend & Canvas UI', requiredSkills: ['TypeScript', 'React'], isFilled: false },
      { id: 'slot_4_3', roleTitle: 'Bioengineering Domain Expert', requiredSkills: ['Python', 'Biology'], isFilled: false },
    ],
    missingRoles: ['Physics & Simulation Lead', 'Web Frontend & Canvas UI'],
    createdAt: '2026-08-15T12:00:00Z',
    updatedAt: '2026-08-21T09:00:00Z',
    matchScore: 68,
    matchHighlights: [
      'Strong TypeScript foundation',
      'Missing core WebGPU/WGSL background',
      'Higher weekly time commitment than usual',
    ],
    matchBreakdown: {
      skillMatch: 60,
      experienceMatch: 75,
      availabilityMatch: 80,
      interestMatch: 65,
      roleMatch: 60,
    },
  },
];
