import { Project } from '@/types/project';
import { StudentProfile } from '@/types/user';
import { Clip } from '@/types/clip';
import { Conversation, ChatMessage } from '@/types/chat';

export const CURRENT_USER: StudentProfile = {
  id: 'usr_curr_01',
  email: 'alex.chen@stanford.edu',
  fullName: 'Alex Chen',
  headline: 'Full-Stack Developer & Product Builder',
  college: 'Stanford University',
  major: 'Computer Science',
  gradYear: 2026,
  experienceLevel: 'junior',
  workingStyle: 'collaborative',
  bio: 'CS junior focused on distributed frontend systems, reactive UI architectures, and human-computer interfaces.',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  githubUrl: 'https://github.com/alexchen',
  portfolioUrl: 'https://alexchen.dev',
  linkedinUrl: 'https://linkedin.com/in/alexchen',
  discordUrl: 'alexchen#1337',
  instagramUrl: 'https://instagram.com/alexchen.dev',
  resumeUrl: 'https://example.com/resumes/alex_chen_resume.pdf',
  followersCount: 24,
  followingCount: 18,
  skills: [
    { id: 'sk_ts', name: 'TypeScript', category: 'frontend', proficiency: 4, yearsExperience: 2.5, verified: true },
    { id: 'sk_next', name: 'Next.js', category: 'frontend', proficiency: 4, yearsExperience: 2.0, verified: true },
    { id: 'sk_react', name: 'React', category: 'frontend', proficiency: 5, yearsExperience: 3.0, verified: true },
    { id: 'sk_tailwind', name: 'Tailwind CSS', category: 'frontend', proficiency: 5, yearsExperience: 2.0, verified: true },
    { id: 'sk_postgres', name: 'PostgreSQL', category: 'backend', proficiency: 3, yearsExperience: 1.5, verified: false },
    { id: 'sk_figma', name: 'UI/UX Design', category: 'design', proficiency: 3, yearsExperience: 1.0, verified: true },
    { id: 'sk_python', name: 'Python', category: 'backend', proficiency: 3, yearsExperience: 2.0, verified: false },
  ],
  interests: [
    { id: 'int_ai', name: 'AI & Human Interaction', category: 'ai' },
    { id: 'int_sys', name: 'Distributed Systems', category: 'systems' },
    { id: 'int_fintech', name: 'Fintech & Tooling', category: 'tools' },
  ],
  availability: {
    hoursPerWeek: 15,
    timezone: 'PST (UTC-8)',
    prefersRemote: true,
    weekendAvailability: true,
    weekdayEvenings: true,
    scheduleWindows: [
      { day: 'monday', startTime: '18:00', endTime: '22:00' },
      { day: 'wednesday', startTime: '18:00', endTime: '22:00' },
      { day: 'saturday', startTime: '10:00', endTime: '17:00' },
    ],
  },
};

export const MOCK_STUDENTS: StudentProfile[] = [
  CURRENT_USER,
  {
    id: 'usr_02',
    email: 'maya.patel@mit.edu',
    fullName: 'Maya Patel',
    headline: 'ML Researcher & PyTorch Specialist',
    college: 'MIT',
    major: 'EECS & AI',
    gradYear: 2025,
    experienceLevel: 'senior',
    workingStyle: 'structured',
    bio: 'Senior doing research in multi-modal vision-language models and edge inference optimization.',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    githubUrl: 'https://github.com/mayapatel',
    linkedinUrl: 'https://linkedin.com/in/mayapatel-ai',
    discordUrl: 'mayapatel_mit',
    followersCount: 42,
    followingCount: 15,
    skills: [
      { id: 'sk_pytorch', name: 'PyTorch', category: 'ml_ai', proficiency: 5, yearsExperience: 3.5, verified: true },
      { id: 'sk_python', name: 'Python', category: 'backend', proficiency: 5, yearsExperience: 4.0, verified: true },
      { id: 'sk_cuda', name: 'CUDA', category: 'ml_ai', proficiency: 3, yearsExperience: 1.5, verified: true },
      { id: 'sk_transformers', name: 'Hugging Face', category: 'ml_ai', proficiency: 4, yearsExperience: 2.0, verified: true },
    ],
    interests: [
      { id: 'int_vision', name: 'Computer Vision', category: 'ai' },
      { id: 'int_robotics', name: 'Autonomous Robotics', category: 'hardware' },
    ],
    availability: {
      hoursPerWeek: 12,
      timezone: 'EST (UTC-5)',
      prefersRemote: true,
      weekendAvailability: true,
      weekdayEvenings: false,
      scheduleWindows: [
        { day: 'tuesday', startTime: '16:00', endTime: '20:00' },
        { day: 'thursday', startTime: '16:00', endTime: '20:00' },
        { day: 'sunday', startTime: '12:00', endTime: '16:00' },
      ],
    },
  },
  {
    id: 'usr_03',
    email: 'marcus.vance@berkeley.edu',
    fullName: 'Marcus Vance',
    headline: 'Systems & Embedded Rust Engineer',
    college: 'UC Berkeley',
    major: 'Computer Science',
    gradYear: 2026,
    experienceLevel: 'junior',
    workingStyle: 'fast-paced',
    bio: 'Low-level systems hacker. Building real-time micro-kernels and high-throughput protocol bridges in Rust.',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    githubUrl: 'https://github.com/marcusv',
    linkedinUrl: 'https://linkedin.com/in/marcus-vance',
    followersCount: 31,
    followingCount: 19,
    skills: [
      { id: 'sk_rust', name: 'Rust', category: 'backend', proficiency: 5, yearsExperience: 3.0, verified: true },
      { id: 'sk_cpp', name: 'C/C++', category: 'hardware', proficiency: 4, yearsExperience: 2.5, verified: true },
      { id: 'sk_grpc', name: 'gRPC & WebSockets', category: 'backend', proficiency: 4, yearsExperience: 2.0, verified: true },
      { id: 'sk_docker', name: 'Docker & Linux', category: 'systems', proficiency: 4, yearsExperience: 2.5, verified: true },
    ],
    interests: [
      { id: 'int_sys', name: 'Distributed Systems', category: 'systems' },
      { id: 'int_iot', name: 'Hardware & IoT', category: 'hardware' },
    ],
    availability: {
      hoursPerWeek: 18,
      timezone: 'PST (UTC-8)',
      prefersRemote: false,
      weekendAvailability: true,
      weekdayEvenings: true,
      scheduleWindows: [
        { day: 'monday', startTime: '19:00', endTime: '23:00' },
        { day: 'wednesday', startTime: '19:00', endTime: '23:00' },
        { day: 'friday', startTime: '19:00', endTime: '23:00' },
        { day: 'saturday', startTime: '13:00', endTime: '19:00' },
      ],
    },
  },
  {
    id: 'usr_04',
    email: 'elena.rostova@cmu.edu',
    fullName: 'Elena Rostova',
    headline: 'Interaction Designer & Design Systems Lead',
    college: 'Carnegie Mellon University',
    major: 'Human-Computer Interaction',
    gradYear: 2025,
    experienceLevel: 'senior',
    workingStyle: 'mentor-oriented',
    bio: 'Designing interfaces that feel tactile, responsive, and humane. Passionate about typography and design systems.',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    portfolioUrl: 'https://elenadesign.space',
    followersCount: 58,
    followingCount: 33,
    skills: [
      { id: 'sk_figma', name: 'UI/UX Design', category: 'design', proficiency: 5, yearsExperience: 4.0, verified: true },
      { id: 'sk_design_sys', name: 'Design Systems', category: 'design', proficiency: 5, yearsExperience: 3.0, verified: true },
      { id: 'sk_tailwind', name: 'Tailwind CSS', category: 'frontend', proficiency: 4, yearsExperience: 2.0, verified: true },
      { id: 'sk_threejs', name: 'Three.js / 3D', category: 'design', proficiency: 3, yearsExperience: 1.5, verified: false },
    ],
    interests: [
      { id: 'int_hci', name: 'HCI & Spatial Design', category: 'design' },
      { id: 'int_edtech', name: 'Accessible EdTech', category: 'social' },
    ],
    availability: {
      hoursPerWeek: 10,
      timezone: 'EST (UTC-5)',
      prefersRemote: true,
      weekendAvailability: false,
      weekdayEvenings: true,
      scheduleWindows: [
        { day: 'tuesday', startTime: '18:00', endTime: '22:00' },
        { day: 'thursday', startTime: '18:00', endTime: '22:00' },
      ],
    },
  },
  // 32+ Fictional Student Profiles for Hackathon Matchmaker
  {
    id: 'usr_05',
    email: 'zack.t@gatech.edu',
    fullName: 'Zack Taylor',
    headline: 'Cybersecurity & Offensive Security Specialist',
    college: 'Georgia Tech',
    major: 'Cybersecurity & CS',
    gradYear: 2026,
    experienceLevel: 'junior',
    workingStyle: 'independent',
    bio: 'CTF team lead. Passionate about reverse engineering, kernel exploit mitigations, and smart contract security.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    githubUrl: 'https://github.com/zacksec',
    followersCount: 19,
    followingCount: 12,
    skills: [
      { id: 'sk_sec', name: 'Network Security', category: 'backend', proficiency: 5, yearsExperience: 3.0, verified: true },
      { id: 'sk_c', name: 'C/C++', category: 'backend', proficiency: 4, yearsExperience: 3.0, verified: true },
      { id: 'sk_py', name: 'Python', category: 'backend', proficiency: 4, yearsExperience: 3.5, verified: true },
      { id: 'sk_sol', name: 'Solidity', category: 'backend', proficiency: 3, yearsExperience: 1.5, verified: false },
    ],
    interests: [{ id: 'int_sec', name: 'Security & Cryptography', category: 'systems' }],
    availability: { hoursPerWeek: 14, timezone: 'EST (UTC-5)', prefersRemote: true, weekendAvailability: true, weekdayEvenings: true },
  },
  {
    id: 'usr_06',
    email: 'sophia.lin@cornell.edu',
    fullName: 'Sophia Lin',
    headline: 'iOS & Swift Spatial UI Developer',
    college: 'Cornell University',
    major: 'Information Science',
    gradYear: 2025,
    experienceLevel: 'senior',
    workingStyle: 'collaborative',
    bio: 'Building visionOS and iOS experiences with SwiftUI and Metal shaders.',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    githubUrl: 'https://github.com/sophialin-dev',
    followersCount: 38,
    followingCount: 22,
    skills: [
      { id: 'sk_swift', name: 'Swift & SwiftUI', category: 'mobile', proficiency: 5, yearsExperience: 4.0, verified: true },
      { id: 'sk_metal', name: 'Metal / Graphics', category: 'mobile', proficiency: 3, yearsExperience: 1.5, verified: false },
      { id: 'sk_ts', name: 'TypeScript', category: 'frontend', proficiency: 4, yearsExperience: 2.0, verified: true },
    ],
    interests: [{ id: 'int_spatial', name: 'Spatial Computing & XR', category: 'mobile' }],
    availability: { hoursPerWeek: 16, timezone: 'EST (UTC-5)', prefersRemote: true, weekendAvailability: true, weekdayEvenings: true },
  },
  {
    id: 'usr_07',
    email: 'devon.park@purdue.edu',
    fullName: 'Devon Park',
    headline: 'Robotics Software & ROS2 Engineer',
    college: 'Purdue University',
    major: 'Robotics Engineering',
    gradYear: 2026,
    experienceLevel: 'junior',
    workingStyle: 'structured',
    bio: 'Autonomous navigation, SLAM pipelines, and path planning algorithms on mobile robot platforms.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    githubUrl: 'https://github.com/devonpark',
    followersCount: 27,
    followingCount: 14,
    skills: [
      { id: 'sk_ros', name: 'ROS / ROS2', category: 'hardware', proficiency: 5, yearsExperience: 2.5, verified: true },
      { id: 'sk_cpp', name: 'C/C++', category: 'hardware', proficiency: 4, yearsExperience: 3.0, verified: true },
      { id: 'sk_python', name: 'Python', category: 'backend', proficiency: 4, yearsExperience: 3.0, verified: true },
    ],
    interests: [{ id: 'int_robo', name: 'Autonomous Robotics', category: 'hardware' }],
    availability: { hoursPerWeek: 12, timezone: 'EST (UTC-5)', prefersRemote: false, weekendAvailability: true, weekdayEvenings: false },
  },
  {
    id: 'usr_08',
    email: 'chloe.dupont@nyu.edu',
    fullName: 'Chloe Dupont',
    headline: 'Product Lead & Startup Growth Hacker',
    college: 'NYU Stern',
    major: 'Business & Technology',
    gradYear: 2025,
    experienceLevel: 'senior',
    workingStyle: 'fast-paced',
    bio: 'Obsessed with product telemetry, conversion funnels, user interviews, and rapid prototyping.',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    linkedinUrl: 'https://linkedin.com/in/chloedupont',
    followersCount: 65,
    followingCount: 40,
    skills: [
      { id: 'sk_prod', name: 'Product Management', category: 'product', proficiency: 5, yearsExperience: 3.0, verified: true },
      { id: 'sk_growth', name: 'Growth Marketing', category: 'marketing', proficiency: 4, yearsExperience: 2.0, verified: true },
      { id: 'sk_sql', name: 'SQL & Analytics', category: 'data', proficiency: 4, yearsExperience: 2.5, verified: true },
    ],
    interests: [{ id: 'int_fintech', name: 'Fintech & Consumer Tech', category: 'product' }],
    availability: { hoursPerWeek: 20, timezone: 'EST (UTC-5)', prefersRemote: true, weekendAvailability: true, weekdayEvenings: true },
  },
  {
    id: 'usr_09',
    email: 'karthik.r@utexas.edu',
    fullName: 'Karthik Rao',
    headline: 'Distributed Go & Kubernetes Cloud Engineer',
    college: 'UT Austin',
    major: 'Electrical & Computer Engineering',
    gradYear: 2026,
    experienceLevel: 'junior',
    workingStyle: 'independent',
    bio: 'Building fault-tolerant backend infrastructure, gRPC services, and event-driven architectures with Kafka.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    githubUrl: 'https://github.com/karthikrao',
    followersCount: 22,
    followingCount: 15,
    skills: [
      { id: 'sk_go', name: 'Golang', category: 'backend', proficiency: 5, yearsExperience: 2.5, verified: true },
      { id: 'sk_k8s', name: 'Kubernetes', category: 'systems', proficiency: 4, yearsExperience: 2.0, verified: true },
      { id: 'sk_postgres', name: 'PostgreSQL', category: 'backend', proficiency: 4, yearsExperience: 2.0, verified: true },
    ],
    interests: [{ id: 'int_cloud', name: 'Cloud Infrastructure', category: 'systems' }],
    availability: { hoursPerWeek: 15, timezone: 'CST (UTC-6)', prefersRemote: true, weekendAvailability: true, weekdayEvenings: true },
  },
  {
    id: 'usr_10',
    email: 'aisha.m@harvard.edu',
    fullName: 'Aisha Mansour',
    headline: 'Bioinformatics & Computational Genomics Lead',
    college: 'Harvard University',
    major: 'Computational Biology',
    gradYear: 2025,
    experienceLevel: 'grad',
    workingStyle: 'structured',
    bio: 'Applying transformer models to protein folding prediction and CRISPR off-target analysis.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    githubUrl: 'https://github.com/aishamansour',
    followersCount: 51,
    followingCount: 29,
    skills: [
      { id: 'sk_py', name: 'Python', category: 'backend', proficiency: 5, yearsExperience: 4.0, verified: true },
      { id: 'sk_bio', name: 'Bioinformatics', category: 'data', proficiency: 5, yearsExperience: 3.5, verified: true },
      { id: 'sk_r', name: 'R & Bioconductor', category: 'data', proficiency: 4, yearsExperience: 3.0, verified: true },
    ],
    interests: [{ id: 'int_bio', name: 'Biotech & Health Sciences', category: 'data' }],
    availability: { hoursPerWeek: 10, timezone: 'EST (UTC-5)', prefersRemote: true, weekendAvailability: true, weekdayEvenings: false },
  },
  {
    id: 'usr_11',
    email: 'lucas.silva@ucla.edu',
    fullName: 'Lucas Silva',
    headline: 'Game Engine & Physics Programmer',
    college: 'UCLA',
    major: 'Computer Science & Media Arts',
    gradYear: 2026,
    experienceLevel: 'junior',
    workingStyle: 'collaborative',
    bio: 'Unity & Unreal developer. Specializing in procedural world generation, HLSL shaders, and multiplayer networking.',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    portfolioUrl: 'https://lucassilva.games',
    followersCount: 33,
    followingCount: 20,
    skills: [
      { id: 'sk_unity', name: 'Unity & C#', category: 'design', proficiency: 5, yearsExperience: 3.5, verified: true },
      { id: 'sk_unreal', name: 'Unreal Engine / C++', category: 'design', proficiency: 4, yearsExperience: 2.0, verified: true },
      { id: 'sk_shaders', name: 'HLSL / Shaders', category: 'design', proficiency: 3, yearsExperience: 1.5, verified: false },
    ],
    interests: [{ id: 'int_games', name: 'Game Dev & Interactive Media', category: 'design' }],
    availability: { hoursPerWeek: 18, timezone: 'PST (UTC-8)', prefersRemote: true, weekendAvailability: true, weekdayEvenings: true },
  },
  {
    id: 'usr_12',
    email: 'priya.s@uiuc.edu',
    fullName: 'Priya Sharma',
    headline: 'Quant & Algorithmic Trading Developer',
    college: 'UIUC',
    major: 'Computer Science & Statistics',
    gradYear: 2025,
    experienceLevel: 'senior',
    workingStyle: 'fast-paced',
    bio: 'High-frequency order book modeling, time-series forecasting with LSTM/XGBoost, and low-latency C++ execution.',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    githubUrl: 'https://github.com/priyasharma-quant',
    followersCount: 47,
    followingCount: 16,
    skills: [
      { id: 'sk_cpp', name: 'C/C++', category: 'backend', proficiency: 5, yearsExperience: 3.5, verified: true },
      { id: 'sk_py', name: 'Python', category: 'backend', proficiency: 5, yearsExperience: 3.5, verified: true },
      { id: 'sk_stats', name: 'Statistical Modeling', category: 'data', proficiency: 5, yearsExperience: 3.0, verified: true },
    ],
    interests: [{ id: 'int_quant', name: 'Quantitative Finance & Algos', category: 'data' }],
    availability: { hoursPerWeek: 15, timezone: 'CST (UTC-6)', prefersRemote: true, weekendAvailability: true, weekdayEvenings: true },
  },
  {
    id: 'usr_13',
    email: 'noah.b@brown.edu',
    fullName: 'Noah Bennett',
    headline: 'Design Engineer & Spline 3D Web Artist',
    college: 'Brown University',
    major: 'Modern Culture & Media',
    gradYear: 2026,
    experienceLevel: 'junior',
    workingStyle: 'mentor-oriented',
    bio: 'Crafting expressive web experiences blending Three.js, GSAP animations, and bespoke brutalist typography.',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    portfolioUrl: 'https://noahbennett.design',
    followersCount: 89,
    followingCount: 45,
    skills: [
      { id: 'sk_threejs', name: 'Three.js / WebGL', category: 'frontend', proficiency: 5, yearsExperience: 3.0, verified: true },
      { id: 'sk_react', name: 'React', category: 'frontend', proficiency: 5, yearsExperience: 3.0, verified: true },
      { id: 'sk_figma', name: 'UI/UX Design', category: 'design', proficiency: 5, yearsExperience: 3.5, verified: true },
    ],
    interests: [{ id: 'int_webgl', name: 'Creative Coding & 3D Web', category: 'design' }],
    availability: { hoursPerWeek: 12, timezone: 'EST (UTC-5)', prefersRemote: true, weekendAvailability: true, weekdayEvenings: true },
  },
  {
    id: 'usr_14',
    email: 'hannah.k@caltech.edu',
    fullName: 'Hannah Kim',
    headline: 'Hardware FPGA & Digital Logic Architect',
    college: 'Caltech',
    major: 'Applied Physics & EE',
    gradYear: 2025,
    experienceLevel: 'senior',
    workingStyle: 'structured',
    bio: 'Designing custom RISC-V accelerators, Verilog testbenches, and high-speed PCIe streaming bridges.',
    avatarUrl: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=150&auto=format&fit=crop&q=80',
    githubUrl: 'https://github.com/hannahkim-ee',
    followersCount: 29,
    followingCount: 11,
    skills: [
      { id: 'sk_verilog', name: 'Verilog / SystemVerilog', category: 'hardware', proficiency: 5, yearsExperience: 3.0, verified: true },
      { id: 'sk_fpga', name: 'FPGA Prototyping', category: 'hardware', proficiency: 4, yearsExperience: 2.5, verified: true },
      { id: 'sk_c', name: 'C/C++', category: 'hardware', proficiency: 4, yearsExperience: 2.5, verified: true },
    ],
    interests: [{ id: 'int_silicon', name: 'Custom Silicon & Computer Architecture', category: 'hardware' }],
    availability: { hoursPerWeek: 14, timezone: 'PST (UTC-8)', prefersRemote: false, weekendAvailability: true, weekdayEvenings: false },
  },
  {
    id: 'usr_15',
    email: 'owen.c@umich.edu',
    fullName: 'Owen Cooper',
    headline: 'Audio DSP & Real-time WebRTC Engineer',
    college: 'University of Michigan',
    major: 'Computer Engineering',
    gradYear: 2026,
    experienceLevel: 'junior',
    workingStyle: 'collaborative',
    bio: 'Low-latency spatial audio DSP, JUCE C++ audio plugins, and interactive WebRTC peer mesh networking.',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    githubUrl: 'https://github.com/owencooper',
    followersCount: 23,
    followingCount: 17,
    skills: [
      { id: 'sk_dsp', name: 'DSP & Audio Filters', category: 'hardware', proficiency: 5, yearsExperience: 2.5, verified: true },
      { id: 'sk_cpp', name: 'C/C++', category: 'backend', proficiency: 4, yearsExperience: 2.5, verified: true },
      { id: 'sk_webrtc', name: 'WebRTC / WebSockets', category: 'backend', proficiency: 4, yearsExperience: 2.0, verified: true },
    ],
    interests: [{ id: 'int_audio', name: 'Acoustics & Spatial Sound', category: 'hardware' }],
    availability: { hoursPerWeek: 16, timezone: 'EST (UTC-5)', prefersRemote: true, weekendAvailability: true, weekdayEvenings: true },
  },
  {
    id: 'usr_16',
    email: 'tara.j@columbia.edu',
    fullName: 'Tara Joshi',
    headline: 'NLP Researcher & LLM Evaluation Lead',
    college: 'Columbia University',
    major: 'Computer Science',
    gradYear: 2025,
    experienceLevel: 'grad',
    workingStyle: 'structured',
    bio: 'LLM alignment, retrieval-augmented generation (RAG) benchmarks, and hallucination reduction methods.',
    avatarUrl: 'https://images.unsplash.com/photo-1534751516642-a171edd25218?w=150&auto=format&fit=crop&q=80',
    githubUrl: 'https://github.com/tarajoshi-nlp',
    followersCount: 62,
    followingCount: 25,
    skills: [
      { id: 'sk_nlp', name: 'NLP & Transformers', category: 'ml_ai', proficiency: 5, yearsExperience: 3.5, verified: true },
      { id: 'sk_py', name: 'Python', category: 'backend', proficiency: 5, yearsExperience: 4.0, verified: true },
      { id: 'sk_rag', name: 'RAG & Vector DBs', category: 'ml_ai', proficiency: 5, yearsExperience: 2.0, verified: true },
    ],
    interests: [{ id: 'int_nlp', name: 'Language Models & Knowledge Graphs', category: 'ai' }],
    availability: { hoursPerWeek: 12, timezone: 'EST (UTC-5)', prefersRemote: true, weekendAvailability: true, weekdayEvenings: true },
  },
  {
    id: 'usr_17',
    email: 'sam.wu@princeton.edu',
    fullName: 'Sam Wu',
    headline: 'Full-Stack GraphQL & React Native Builder',
    college: 'Princeton University',
    major: 'Computer Science',
    gradYear: 2026,
    experienceLevel: 'junior',
    workingStyle: 'fast-paced',
    bio: 'Shipping cross-platform mobile apps with React Native, Relay/GraphQL, and offline-first SQLite synchronization.',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    githubUrl: 'https://github.com/samwu',
    followersCount: 35,
    followingCount: 21,
    skills: [
      { id: 'sk_rn', name: 'React Native', category: 'mobile', proficiency: 5, yearsExperience: 3.0, verified: true },
      { id: 'sk_ts', name: 'TypeScript', category: 'frontend', proficiency: 5, yearsExperience: 3.0, verified: true },
      { id: 'sk_graphql', name: 'GraphQL', category: 'backend', proficiency: 4, yearsExperience: 2.0, verified: true },
    ],
    interests: [{ id: 'int_mobile', name: 'Mobile Systems & Local-First', category: 'mobile' }],
    availability: { hoursPerWeek: 15, timezone: 'EST (UTC-5)', prefersRemote: true, weekendAvailability: true, weekdayEvenings: true },
  },
  {
    id: 'usr_18',
    email: 'fatima.a@uw.edu',
    fullName: 'Fatima Al-Hassan',
    headline: 'Satellite Remote Sensing & Climate Data Analyst',
    college: 'University of Washington',
    major: 'Environmental Informatics',
    gradYear: 2025,
    experienceLevel: 'senior',
    workingStyle: 'collaborative',
    bio: 'Analyzing hyperspectral Earth observation feeds using GeoPandas, Xarray, and Sentinel-2 satellite imagery.',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    githubUrl: 'https://github.com/fatima-geo',
    followersCount: 41,
    followingCount: 28,
    skills: [
      { id: 'sk_gis', name: 'GIS & Remote Sensing', category: 'data', proficiency: 5, yearsExperience: 3.0, verified: true },
      { id: 'sk_py', name: 'Python & Pandas', category: 'data', proficiency: 5, yearsExperience: 3.5, verified: true },
      { id: 'sk_cv', name: 'Computer Vision', category: 'ml_ai', proficiency: 4, yearsExperience: 2.0, verified: true },
    ],
    interests: [{ id: 'int_climate', name: 'Climate Tech & Geospatial AI', category: 'data' }],
    availability: { hoursPerWeek: 14, timezone: 'PST (UTC-8)', prefersRemote: true, weekendAvailability: true, weekdayEvenings: false },
  },
  {
    id: 'usr_19',
    email: 'leo.morales@upenn.edu',
    fullName: 'Leo Morales',
    headline: 'Fintech Backend & High-Throughput Ledger Engineer',
    college: 'University of Pennsylvania',
    major: 'Computer Science & Finance',
    gradYear: 2026,
    experienceLevel: 'junior',
    workingStyle: 'structured',
    bio: 'Building double-entry bookkeeping ledgers, ACID transaction pipelines, and real-time fraud detection systems.',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    githubUrl: 'https://github.com/leomorales',
    followersCount: 28,
    followingCount: 18,
    skills: [
      { id: 'sk_postgres', name: 'PostgreSQL & SQL', category: 'backend', proficiency: 5, yearsExperience: 3.0, verified: true },
      { id: 'sk_go', name: 'Golang', category: 'backend', proficiency: 4, yearsExperience: 2.0, verified: true },
      { id: 'sk_redis', name: 'Redis / In-Memory Cache', category: 'backend', proficiency: 4, yearsExperience: 2.0, verified: true },
    ],
    interests: [{ id: 'int_fintech', name: 'Fintech & Payment Rails', category: 'systems' }],
    availability: { hoursPerWeek: 15, timezone: 'EST (UTC-5)', prefersRemote: true, weekendAvailability: true, weekdayEvenings: true },
  },
  {
    id: 'usr_20',
    email: 'nina.z@duke.edu',
    fullName: 'Nina Zhang',
    headline: 'Biomedical Sensing & Wearables Engineer',
    college: 'Duke University',
    major: 'Biomedical Engineering',
    gradYear: 2025,
    experienceLevel: 'senior',
    workingStyle: 'mentor-oriented',
    bio: 'Designing non-invasive PPG/ECG sensor circuits, Bluetooth Low Energy firmware, and clinical health dashboards.',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    followersCount: 37,
    followingCount: 20,
    skills: [
      { id: 'sk_ble', name: 'Embedded C / BLE', category: 'hardware', proficiency: 5, yearsExperience: 3.0, verified: true },
      { id: 'sk_pcb', name: 'PCB Layout (KiCad)', category: 'hardware', proficiency: 4, yearsExperience: 2.5, verified: true },
      { id: 'sk_py', name: 'Python Signal Processing', category: 'data', proficiency: 4, yearsExperience: 2.5, verified: true },
    ],
    interests: [{ id: 'int_health', name: 'MedTech & Biosensors', category: 'hardware' }],
    availability: { hoursPerWeek: 12, timezone: 'EST (UTC-5)', prefersRemote: false, weekendAvailability: true, weekdayEvenings: true },
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj_01',
    ownerId: 'usr_02',
    owner: MOCK_STUDENTS[1],
    title: 'EchoSpatial: Spatial Audio for Visual Impairment',
    tagline: 'Real-time LiDAR depth mapping converted into directional 3D audio cues.',
    description: 'We are engineering an iOS and wearable spatial audio beacon system that translates LiDAR point clouds into synthesized binaural soundscapes. It enables visually impaired students to navigate indoor university buildings autonomously with sub-meter acoustic precision.',
    category: 'Assistive Tech & Vision',
    status: 'recruiting',
    maxTeamSize: 4,
    durationWeeks: 8,
    hoursPerWeek: 12,
    bannerUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    githubRepo: 'https://github.com/echospatial/core',
    demoUrl: 'https://echospatial.internal.io',
    requiredSkills: [
      { skill: { id: 'sk_ts', name: 'TypeScript', category: 'frontend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_react', name: 'React', category: 'frontend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_pytorch', name: 'PyTorch', category: 'ml_ai' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_figma', name: 'UI/UX Design', category: 'design' }, requiredProficiency: 3, importance: 'preferred' },
    ],
    slots: [
      { id: 'slot_1', roleTitle: 'Spatial ML Lead', assignedMember: MOCK_STUDENTS[1], requiredSkills: ['PyTorch', 'Python'], isFilled: true },
      { id: 'slot_2', roleTitle: 'Lead Web/App Architect', requiredSkills: ['TypeScript', 'React', 'Next.js'], isFilled: false },
      { id: 'slot_3', roleTitle: 'HCI & Accessibility Designer', requiredSkills: ['UI/UX Design', 'Figma'], isFilled: false },
      { id: 'slot_4', roleTitle: 'Acoustics & DSP Engineer', requiredSkills: ['C/C++', 'DSP'], isFilled: false },
    ],
    missingRoles: ['Lead Web/App Architect', 'HCI & Accessibility Designer'],
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-08-24T14:30:00Z',
    matchScore: 94,
    matchHighlights: [
      'Top skill match: TypeScript (Level 4) & React (Level 5)',
      '15h/wk exceeds 12h/wk requirement',
      'High assistive tech interest alignment',
    ],
    matchBreakdown: {
      skillMatch: 95,
      experienceMatch: 90,
      availabilityMatch: 100,
      interestMatch: 95,
      roleMatch: 90,
    },
  },
  {
    id: 'proj_02',
    ownerId: 'usr_03',
    owner: MOCK_STUDENTS[2],
    title: 'KubePulse: Zero-Overhead Distributed Cluster Mesh',
    tagline: 'Lightweight, single-binary container orchestration engine for student labs.',
    description: 'Existing cluster engines consume 2GB+ per node just for control planes. KubePulse is built ground-up in Rust with eBPF telemetry to run resilient distributed workloads on recycled campus hardware under 30MB baseline RAM.',
    category: 'Systems & Infrastructure',
    status: 'recruiting',
    maxTeamSize: 3,
    durationWeeks: 10,
    hoursPerWeek: 15,
    bannerUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    githubRepo: 'https://github.com/kubepulse/core',
    requiredSkills: [
      { skill: { id: 'sk_rust', name: 'Rust', category: 'backend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_ts', name: 'TypeScript', category: 'frontend' }, requiredProficiency: 3, importance: 'preferred' },
      { skill: { id: 'sk_tailwind', name: 'Tailwind CSS', category: 'frontend' }, requiredProficiency: 3, importance: 'nice_to_have' },
    ],
    slots: [
      { id: 'slot_2_1', roleTitle: 'Core Systems & eBPF Lead', assignedMember: MOCK_STUDENTS[2], requiredSkills: ['Rust', 'C/C++'], isFilled: true },
      { id: 'slot_2_2', roleTitle: 'Dashboard & Visualizer Engineer', requiredSkills: ['TypeScript', 'Next.js', 'Tailwind CSS'], isFilled: false },
      { id: 'slot_2_3', roleTitle: 'Distributed Testing Engineer', requiredSkills: ['Docker', 'Linux', 'Rust'], isFilled: false },
    ],
    missingRoles: ['Dashboard & Visualizer Engineer'],
    createdAt: '2026-08-18T16:00:00Z',
    updatedAt: '2026-08-23T11:20:00Z',
    matchScore: 86,
    matchHighlights: [
      'Frontend & Dashboard builder needed',
      'Perfect schedule fit (15h/wk)',
      'Direct match for TypeScript + Tailwind',
    ],
    matchBreakdown: {
      skillMatch: 82,
      experienceMatch: 88,
      availabilityMatch: 100,
      interestMatch: 85,
      roleMatch: 85,
    },
  },
  {
    id: 'proj_03',
    ownerId: 'usr_04',
    owner: MOCK_STUDENTS[3],
    title: 'OmniCampus: Decentralized University Course Graph',
    tagline: 'Interactive 3D graph connecting prerequisite pathways and research labs.',
    description: 'Course catalogs are static PDFs. OmniCampus parses thousands of syllabus documents across 12 universities into a semantic prerequisite graph with interactive WebGL visualization, community course reviews, and workload balancing.',
    category: 'EdTech & Knowledge Graphs',
    status: 'recruiting',
    maxTeamSize: 4,
    durationWeeks: 6,
    hoursPerWeek: 10,
    bannerUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    githubRepo: 'https://github.com/omnicampus/graph',
    requiredSkills: [
      { skill: { id: 'sk_next', name: 'Next.js', category: 'frontend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_postgres', name: 'PostgreSQL', category: 'backend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_ts', name: 'TypeScript', category: 'frontend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_figma', name: 'UI/UX Design', category: 'design' }, requiredProficiency: 4, importance: 'preferred' },
    ],
    slots: [
      { id: 'slot_3_1', roleTitle: 'Design & Interaction Lead', assignedMember: MOCK_STUDENTS[3], requiredSkills: ['UI/UX Design', 'Figma'], isFilled: true },
      { id: 'slot_3_2', roleTitle: 'Full-Stack Next.js Architect', requiredSkills: ['Next.js', 'TypeScript', 'PostgreSQL'], isFilled: false },
      { id: 'slot_3_3', roleTitle: 'Graph Algorithm & Data Pipeline', requiredSkills: ['Python', 'PostgreSQL'], isFilled: false },
    ],
    missingRoles: ['Full-Stack Next.js Architect'],
    createdAt: '2026-08-22T08:00:00Z',
    updatedAt: '2026-08-25T02:15:00Z',
    matchScore: 97,
    matchHighlights: [
      'Exact tech stack alignment: Next.js + TypeScript + PostgreSQL',
      'High demand for full-stack role',
      'Active Stanford/CMU cross-campus collaboration',
    ],
    matchBreakdown: {
      skillMatch: 98,
      experienceMatch: 95,
      availabilityMatch: 100,
      interestMatch: 96,
      roleMatch: 98,
    },
  },
  {
    id: 'proj_04',
    ownerId: 'usr_02',
    owner: MOCK_STUDENTS[1],
    title: 'BioFlow: Microfluidics Simulation Playground',
    tagline: 'GPU-accelerated droplet physics engine running directly in browser WebGPU.',
    description: 'Democratizing lab-on-a-chip prototyping. Instead of weeks of physical cleanroom trial-and-error, BioFlow allows bioengineering students to simulate microfluidic laminar flow, droplet merging, and cell sorting in sub-millisecond frames.',
    category: 'Biotech & Scientific Computing',
    status: 'recruiting',
    maxTeamSize: 4,
    durationWeeks: 12,
    hoursPerWeek: 16,
    bannerUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop&q=80',
    requiredSkills: [
      { skill: { id: 'sk_webgpu', name: 'WebGPU / WGSL', category: 'frontend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_ts', name: 'TypeScript', category: 'frontend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_python', name: 'Python', category: 'backend' }, requiredProficiency: 3, importance: 'preferred' },
    ],
    slots: [
      { id: 'slot_4_1', roleTitle: 'Physics & Simulation Lead', requiredSkills: ['WebGPU', 'C++'], isFilled: false },
      { id: 'slot_4_2', roleTitle: 'Web Frontend & Canvas UI', requiredSkills: ['TypeScript', 'React'], isFilled: false },
      { id: 'slot_4_3', roleTitle: 'Bioengineering Domain Expert', requiredSkills: ['Python', 'Biology'], isFilled: false },
    ],
    missingRoles: ['Physics & Simulation Lead', 'Web Frontend & Canvas UI'],
    createdAt: '2026-08-15T12:00:00Z',
    updatedAt: '2026-08-21T09:00:00Z',
    matchScore: 68,
    matchHighlights: [
      'Strong TypeScript foundation',
      'Missing core WebGPU/WGSL background',
      'Higher weekly time commitment than usual',
    ],
    matchBreakdown: {
      skillMatch: 60,
      experienceMatch: 75,
      availabilityMatch: 80,
      interestMatch: 65,
      roleMatch: 60,
    },
  },
  {
    id: 'proj_05',
    ownerId: 'usr_07',
    owner: MOCK_STUDENTS[6],
    title: 'AeroSwarm: Autonomous Micro-UAV Mesh Network',
    tagline: 'Decentralized drone swarm formation algorithms running over ultra-wideband radio.',
    description: 'Developing decentralized flocking, collision avoidance, and search-and-rescue mapping for autonomous drone swarms without central ground stations.',
    category: 'Robotics & Embedded IoT',
    status: 'recruiting',
    maxTeamSize: 4,
    durationWeeks: 10,
    hoursPerWeek: 14,
    bannerUrl: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop&q=80',
    requiredSkills: [
      { skill: { id: 'sk_ros', name: 'ROS / ROS2', category: 'hardware' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_cpp', name: 'C/C++', category: 'hardware' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_py', name: 'Python', category: 'backend' }, requiredProficiency: 3, importance: 'preferred' },
    ],
    slots: [
      { id: 'slot_5_1', roleTitle: 'Swarm Flight Controller Lead', requiredSkills: ['C/C++', 'ROS'], isFilled: true },
      { id: 'slot_5_2', roleTitle: 'Ground Station UI Engineer', requiredSkills: ['TypeScript', 'React'], isFilled: false },
    ],
    missingRoles: ['Ground Station UI Engineer'],
    createdAt: '2026-08-21T11:00:00Z',
    updatedAt: '2026-08-25T14:00:00Z',
    matchScore: 88,
    matchHighlights: ['Ground station dashboard developer needed', 'Strong React/TypeScript fit'],
  },
  {
    id: 'proj_06',
    ownerId: 'usr_08',
    owner: MOCK_STUDENTS[7],
    title: 'PebblePay: Tap-to-Split Microtransactions for Students',
    tagline: 'Near-field peer-to-peer campus payments with zero merchant processing fees.',
    description: 'Instant group tab splitting and cafeteria payments using localized secure BLE handshakes and zero-fee layer-2 state channels.',
    category: 'Fintech & Smart Contracts',
    status: 'recruiting',
    maxTeamSize: 3,
    durationWeeks: 8,
    hoursPerWeek: 12,
    bannerUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&auto=format&fit=crop&q=80',
    requiredSkills: [
      { skill: { id: 'sk_ts', name: 'TypeScript', category: 'frontend' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_mobile', name: 'React Native / iOS', category: 'mobile' }, requiredProficiency: 4, importance: 'required' },
      { skill: { id: 'sk_sec', name: 'Cryptography & Auth', category: 'backend' }, requiredProficiency: 3, importance: 'preferred' },
    ],
    slots: [
      { id: 'slot_6_1', roleTitle: 'Product & Growth Lead', requiredSkills: ['Product Management'], isFilled: true },
      { id: 'slot_6_2', roleTitle: 'Lead Mobile Engineer', requiredSkills: ['React Native', 'TypeScript'], isFilled: false },
    ],
    missingRoles: ['Lead Mobile Engineer'],
    createdAt: '2026-08-22T15:00:00Z',
    updatedAt: '2026-08-26T09:00:00Z',
    matchScore: 91,
    matchHighlights: ['High frontend & mobile alignment', 'Matches Fintech tooling interest'],
  },
];

export const MOCK_CLIPS: Clip[] = [
  {
    id: 'clip_01',
    creatorId: 'usr_02',
    creator: MOCK_STUDENTS[1],
    projectId: 'proj_01',
    project: MOCK_PROJECTS[0],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    caption: 'Live demo of our LiDAR spatial sound beacon! Sub-meter acoustic directional guidance working in the MIT infinite corridor. 🔊✨',
    tags: ['AssistiveTech', 'SpatialAudio', 'LiDAR', 'Demo'],
    likesCount: 142,
    isLiked: false,
    createdAt: '2026-08-24T18:00:00Z',
  },
  {
    id: 'clip_02',
    creatorId: 'usr_03',
    creator: MOCK_STUDENTS[2],
    projectId: 'proj_02',
    project: MOCK_PROJECTS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    caption: 'KubePulse node failover test under heavy simulated DDoS. Recovered in under 4ms on a Raspberry Pi 4 cluster! 🦀🚀',
    tags: ['Rust', 'DistributedSystems', 'eBPF', 'KubePulse'],
    likesCount: 98,
    isLiked: true,
    createdAt: '2026-08-25T12:30:00Z',
  },
  {
    id: 'clip_03',
    creatorId: 'usr_04',
    creator: MOCK_STUDENTS[3],
    projectId: 'proj_03',
    project: MOCK_PROJECTS[2],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    caption: 'OmniCampus 3D syllabus graph rendering 4,500 courses in WebGPU. Smooth 120 FPS traversal on iPad Pro! 🕸️📚',
    tags: ['ThreeJS', 'WebGPU', 'HCI', 'EdTech'],
    likesCount: 215,
    isLiked: false,
    createdAt: '2026-08-26T09:15:00Z',
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_01',
    name: 'Maya Patel',
    isGroup: false,
    members: [
      { conversationId: 'conv_01', userId: CURRENT_USER.id, joinedAt: '2026-08-20T10:00:00Z' },
      { conversationId: 'conv_01', userId: 'usr_02', user: MOCK_STUDENTS[1], joinedAt: '2026-08-20T10:00:00Z' },
    ],
    lastMessage: {
      id: 'msg_01',
      conversationId: 'conv_01',
      senderId: 'usr_02',
      content: 'Hey Alex! Checked your profile—love your React & Next.js background. Want to lead the web app for EchoSpatial?',
      createdAt: '2026-08-25T14:20:00Z',
    },
    unreadCount: 1,
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-08-25T14:20:00Z',
  },
  {
    id: 'conv_02',
    name: 'Marcus Vance',
    isGroup: false,
    members: [
      { conversationId: 'conv_02', userId: CURRENT_USER.id, joinedAt: '2026-08-22T08:00:00Z' },
      { conversationId: 'conv_02', userId: 'usr_03', user: MOCK_STUDENTS[2], joinedAt: '2026-08-22T08:00:00Z' },
    ],
    lastMessage: {
      id: 'msg_02',
      conversationId: 'conv_02',
      senderId: CURRENT_USER.id,
      content: 'The eBPF metrics look super clean. Let me know when you push the dashboard contract.',
      createdAt: '2026-08-24T19:45:00Z',
    },
    unreadCount: 0,
    createdAt: '2026-08-22T08:00:00Z',
    updatedAt: '2026-08-24T19:45:00Z',
  },
  {
    id: 'conv_group_01',
    name: 'EchoSpatial Core Squad 🚀',
    isGroup: true,
    members: [
      { conversationId: 'conv_group_01', userId: CURRENT_USER.id, joinedAt: '2026-08-21T09:00:00Z' },
      { conversationId: 'conv_group_01', userId: 'usr_02', user: MOCK_STUDENTS[1], joinedAt: '2026-08-21T09:00:00Z' },
      { conversationId: 'conv_group_01', userId: 'usr_04', user: MOCK_STUDENTS[3], joinedAt: '2026-08-21T09:00:00Z' },
    ],
    lastMessage: {
      id: 'msg_03',
      conversationId: 'conv_group_01',
      senderId: 'usr_04',
      content: 'I uploaded the new high-contrast UI tokens to Figma. Take a look when you can!',
      createdAt: '2026-08-26T10:05:00Z',
    },
    unreadCount: 2,
    createdAt: '2026-08-21T09:00:00Z',
    updatedAt: '2026-08-26T10:05:00Z',
  },
];

export const MOCK_MESSAGES: Record<string, ChatMessage[]> = {
  conv_01: [
    {
      id: 'msg_1_1',
      conversationId: 'conv_01',
      senderId: 'usr_02',
      content: 'Hey Alex! Checked your profile—love your React & Next.js background. Want to lead the web app for EchoSpatial?',
      createdAt: '2026-08-25T14:20:00Z',
    },
  ],
  conv_02: [
    {
      id: 'msg_2_1',
      conversationId: 'conv_02',
      senderId: 'usr_03',
      content: 'Hey Alex, are you familiar with WebSockets and real-time streaming buffers?',
      createdAt: '2026-08-24T19:30:00Z',
    },
    {
      id: 'msg_2_2',
      conversationId: 'conv_02',
      senderId: CURRENT_USER.id,
      content: 'The eBPF metrics look super clean. Let me know when you push the dashboard contract.',
      createdAt: '2026-08-24T19:45:00Z',
    },
  ],
  conv_group_01: [
    {
      id: 'msg_g_1',
      conversationId: 'conv_group_01',
      senderId: 'usr_02',
      content: 'Welcome to the EchoSpatial sprint group everyone! Let’s crush this prototype.',
      createdAt: '2026-08-21T09:10:00Z',
    },
    {
      id: 'msg_g_2',
      conversationId: 'conv_group_01',
      senderId: 'usr_04',
      content: 'I uploaded the new high-contrast UI tokens to Figma. Take a look when you can!',
      createdAt: '2026-08-26T10:05:00Z',
    },
  ],
};
